src/components.d.ts
src/components/column/AppCol.tsx
src/components/image/AppImage.tsx
src/components/position/AppPos.tsx
src/components/random/AppRandom.tsx
src/components/root/assets/xmlData.xml
src/components/row/AppRow.tsx
src/components/shape/AppShape.tsx
src/components/text/AppText.tsx
src/components/wrap/AppWrap.tsx
src/utils/css/animation.css
src/utils/utils.ts

**isContinueOnCorrect:**
- Validates whether the current action or step is correct.
**isAllowOnlyCorrect:**
- Restricts drag-and-drop actions to accept only correct items.
- If an incorrect item is dropped, the system will return the item to its original position.
**onMatch:**
- Removing "onMatch" events.

working with "isContinueOncorrect" and "isAllowOnlyCorrect"

---

src/utils/utils.ts

- Fixed the drag and drop issue by updating relevant drag-related code.
- Created the appendingDragElementsInDrop() function to append dragged elements into the drop area after the action is completed.

Fix Drag and Drop issue

---

src/components/root/assets/xmlData.xml
src/utils/utils.ts

- Users can drag elements within the boundaries of their parent container.
- Movement is scaled correctly based on the parent element's scaling factor.
- Ensures elements stay within the visible area of their parent container during dragging.
- Detects overlap between draggable elements and identifies the most overlapped element dynamically.
- Automatically swaps the positions of overlapping elements when the drag action ends.
- Updates the arrangement of elements in localStorage after a successful swap, ensuring state consistency across sessions.
- Triggers slideCompleted to validate the correctness of the new arrangement based on predefined objectives.

Working on slide type

---

src/components.d.ts
src/components/column/lido-col.tsx
src/components/container/lido-container.tsx
src/components/home/lido-home.tsx
src/components/image/lido-image.tsx
src/components/position/lido-pos.tsx
src/components/random/lido-random.tsx
src/components/root/lido-root.tsx
src/components/row/lido-row.tsx
src/components/shape/lido-shape.tsx
src/components/text/lido-text.tsx
src/components/trace/lido-trace.tsx
src/components/wrap/lido-wrap.tsx
src/index.html

- In the lido-container component, I set canplay as an attribute.
- Changed all components class names App to Lido.

Working on canplay

---

src/components.d.ts
src/components/root/assets/xmlData.xml
src/utils/utils.ts

- Fixed the issue with storing values.
- Updated the XML file.
- Resolved the clicking issue in the drag-and-drop feature.

Fixed the lido player issues

---

src/components/root/assets/xmlData.xml

- Updated onCorrect and onIncorrect value in multiple option Template

Updated XML file

---

src/components/root/assets/xmlData.xml

Update xml file

---

src/components.d.ts
src/components/column/lido-col.tsx
src/components/root/assets/xmlData.xml
src/components/row/lido-row.css
src/components/row/lido-row.tsx
src/components/wrap/lido-wrap.tsx
src/utils/utils.ts

- **childElementsLength**
> The number of child elements that should be displayed inside the row. This value is dynamically adjusted based on `minLength` and `maxLength`
- **minLength**
> The minimum number of child elements that must be displayed inside the row.
- **maxLength**
> The maximum number of child elements that can be displayed inside the row.
- xml file updated..

Create few Attributes

---

src/components.d.ts
src/components/container/lido-container.tsx
src/index.css

- Add and update Background Image functionality for both landscape and portrait support.

Upadeted Background image functionlity

---

src/components.d.ts
src/components/image/lido-image.css
src/components/image/lido-image.tsx
src/components/image/readme.md
src/components/root/assets/xmlData.xml
src/utils/utils.ts

- Added slice support image component itself
- Fixed some issue from drag and drop

Added slice support for lido player

---

src/components/image/lido-image.css
stencil.config.ts

Update lido-image.css file

---

src/stories/Templates/puzzleGame/puzzleGame.stories.ts

puzzle game storybook

---

package-lock.json
package.json
src/assets/index.xml
src/components.d.ts
src/components/container/lido-container.css
src/components/float/lido-float.css
src/components/float/lido-float.tsx
src/components/float/readme.md
src/components/home/lido-home.tsx
src/components/home/readme.md
src/components/image/lido-image.tsx
src/components/image/readme.md
src/components/root/readme.md
src/index.html
src/stories/Templates/balloonPop/balloonPop.stories.ts
src/utils/constants.ts
src/utils/utils.ts
src/utils/utilsHandlers/clickHandler.ts
src/utils/utilsHandlers/dragDropHandler.ts
src/utils/utilsHandlers/floatHandler.ts
src/utils/utilsHandlers/slideHandler.ts
src/utils/utilsHandlers/sortHandler.ts

- Created a new component: <lido-float /> to support floating behavior.
- Installed the "css-filter-convert" package to assist with CSS filter conversions.
- Added: Story Book support for Balloonpop

Added: Float support

---

src/stories/Templates/grid/grid.stories.ts

Created Grid UI

---

src/stories/Templates/letterboard/letterboard.stories.ts

letterboard storybook

---

src/stories/Templates/openwindow.stories.ts

Created OpenWindow UI

---

src/utils/utils.ts

Am setting the score as 100. and calling executeActions function and moves to the next container.

Setting Score if objective is Absent.

---

src/assets/index.xml
src/css/index.css
src/utils/utils.ts
src/utils/utilsHandlers/dragDropHandler.ts

when isAllowOnlyDrop is made true, the element will get dropped only if te drag value and drop value matches, else the drag value animates from drop area to its original position

animating-dragElement if value doesnt matches

---

src/stories/Templates/spellDoor/spellDoor.stories.ts

fix : spellDoor issues

---

src/stories/Templates/LetterPairing/LetterPairing.stories.ts

changed controls for the story book now It is easily recognizable where to add text and where to add image.

Given exact controlls for storybook

---

src/assets/index.xml
src/components/image/readme.md
src/utils/utilsHandlers/dragDropHandler.ts

In fillUp template, drop options were not resizing when drag element was moved to another drop element.

Resolved resizing issue

---

src/components/home/lido-home.css
src/components/home/lido-home.tsx
src/utils/utils.ts

Previously while parent audio for all elements is playing at that time if we press individual audio the parent audio is not stopping immediately so I fixed that issue and the navbar is taking lot of height so that the audio for question is not clickable so i set height so it won't effect anything.

I have fixed audio issue and navbar height.

---

src/stories/Templates/LetterPairing/LetterPairing.stories.ts

In letter pairing template, worked on drag and drop elements that if both img and text is not present in drag or drop element then it should not render.

Worked on drag and drop cell

---

src/components/home/lido-home.css
src/components/home/lido-home.tsx

Given support for normal full screen and lanAI

updated navbar for LanAI

---

src/components/home/lido-home.tsx

increased the time settimout

---

src/assets/index.xml
src/stories/Templates/letterboard/letterboard.stories.ts
src/stories/Templates/puzzleGame/puzzleGame.stories.ts
src/utils/utilsHandlers/dragDropHandler.ts

letterboard-storybook

---

src/stories/Templates/Fill-Up/fill-up.stories.ts
src/stories/Templates/letterboard/letterboard.stories.ts
src/stories/Templates/spellDoor/spellDoor.stories.ts
src/utils/utilsHandlers/dragDropHandler.ts

1)-----fillUp- when  their is no image according to the width of the text , the parent white box
2)-----letter Board issues
when is-allow-only-correct = true given , when we drag the element on right drop and again if we drag the same element on wrong drop, visually it was reseting to its original place but code wise it was not

fillup storybook and letterboardIssues

---

src/stories/Templates/multipleOption/mcqWithQuestionImage.stories.ts

Update mcq template

---

src/assets/index.xml
src/stories/Templates/jumpSentence/jumpSentence.stories.ts

Added audio playback to activity —  audio now plays automatically on entry and replays on correct completion along with success animation.

Audio-support
